config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#index'
  get 'books/find', as: 'books_find'
  get '/info/:info', to: 'books#info', as: 'find_info'
  get '/omypage', to: 'books#old_mypage', as: 'old_mypage'
  get '/mypage', to: 'books#mypage', as: 'mypage'
  get '/hello', to: 'books#introduction', as: 'intro'
  get '/sgmail', to: 'books#sgmail', as: 'sgmail'

  resources :books do
  	post '/like', to: 'books#like_toggle'
    post '/sell', to: 'books#sell'
    resources :comments, only: [:create, :destroy, :edit, :update] do
      resources :replies, only: [:new, :create, :destroy, :edit, :update]
    end
  end
  resources :conversations, only: [:create] do
  	member do
  		post :close
  	end
  	resources :messages, only: [:create]
  end
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  resources :new_notifications
end

app/models/reply.rb
class Reply < ApplicationRecord
  validates :content, presence: true
  belongs_to :comment
  belongs_to :user
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_user!
  def new
  	@comment = Comment.find(params[:comment_id])
  	@book = Book.find(params[:book_id])
  	@reply = Reply.new
  end
  def create
    @book = Book.find(params[:book_id])
    @comment = Comment.find(params[:comment_id])
    @reply = @comment.replies.build(reply_params)
    @reply.user_id = current_user.id
    @reply.save

    # if @comment.user_id != current_user.id
      @new_notification = NewNotification.create! user: @comment.user, content: "#{current_user.username}님이 회원님의 댓글에 대댓글을 달았습니다. (#{@book.bookname})" ,content_truncate: "#{current_user.username}님이 회원님의 댓글에 대댓글을 달았습니다. (#{@book.bookname})".truncate(20, omission: '...'), link: book_path(@book)
    # end

    redirect_to "/books/#{@book.id}/#reply-#{@reply.id}"

  end
  def destroy
    @reply = Reply.find(params[:id])
    @id = @reply.comment.book.id
    @reply.destroy
    redirect_to "/books/#{@id}#comment-box"
  end
  def edit
    @reply = Reply.find(params[:id])
  end
  def update 
    @reply = Reply.find(params[:id])
    @comment = @reply.comment
    @book = @comment.book
    @reply.update(reply_params)
  end


    private
  def reply_params
    params.require(:reply).permit(:content, :comment_id)
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_edit_form.html.erb
<%= form_for [@reply.comment.book,@reply.comment, @reply], remote: true do |f| %>
  	 <strong><%= @reply.user.username %></strong> : <%= f.text_field :content %>
   	 <%= f.submit %>
<% end %>

app/views/replies/_form.html.erb
<%= form_for [@book, @comment, @comment.replies.new] do |f| %>
	<% comment_id = @comment.id%>
	<%= f.text_field :content, class: "repl_content", id: "reply_content-#{comment_id}", :autocomplete => :off,:required => true %>
	<%= f.submit "작성", class:"repl" %>
<% end %>

app/views/replies/_item.html.erb
<li>  
	<div id="reply-<%=reply.id%>" class="ml-4">
    <span style="margin-right: 1%;"%>ㄴ</span><strong><%= reply.user.username %></strong> <%= reply.content %><br>
    <% if reply.user == current_user %>
    <%= link_to "삭제", book_comment_reply_path(book, comment, reply), id: 'cmt',method: :delete %>
    <% end %>
    </div>
</li>  

app/views/replies/_update_item.html.erb
<li>  
	<div id="reply-<%=reply.id%>">
    <strong><%= reply.user.username %></strong> : <%= reply.content %>
    <% if reply.user == current_user %>
    <%= link_to "수정", edit_book_comment_reply_path(book, comment, reply), remote: true %>
    <%= link_to "삭제", book_comment_reply_path(book, comment, reply), remote: true, method: :delete %>
    <% end %>
    </div>
</li>  

app/views/replies/create.js.erb
(function($){
    // $("#reply_content-<%=@comment.id%>").val("");
    $("#new_reply").remove();
    var html = "<%= escape_javascript(render(partial: 'replies/item', locals: {book: @book, comment: @comment, reply: @reply})) %>";
    $(".replies-comment-<%=@comment.id%>").append(html);
})(jQuery)

app/views/replies/destroy.js.erb
(function($){
    $('#reply-<%= @reply.id %>').remove();
})(jQuery)

app/views/replies/edit.js.erb
(function($){
    $('#reply-<%= @reply.id %>').html("<%= j render 'edit_form' %>");
})(jQuery)

app/views/replies/new.js.erb
(function($){
	$('#comment-<%=@comment.id %> > a.reply-comment-link').hide();
    $('#comment-<%=@comment.id %>-replyform').append("<%= j render 'form' %>");
})(jQuery)

app/views/replies/update.js.erb
(function($){
    var html = "<%= escape_javascript(render(partial: 'replies/update_item', locals: {book: @book, comment: @comment, reply: @reply})) %>";
    $("#edit_reply_<%=@reply.id%>").replaceWith(html);
})(jQuery)