config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#index'
  get 'books/find', as: 'books_find'
  get '/info/:info', to: 'books#info', as: 'find_info'
  get '/omypage', to: 'books#old_mypage', as: 'old_mypage'
  get '/mypage', to: 'books#mypage', as: 'mypage'
  get '/hello', to: 'books#introduction', as: 'intro'
  get '/sgmail', to: 'books#sgmail', as: 'sgmail'

  resources :books do
  	post '/like', to: 'books#like_toggle'
    post '/sell', to: 'books#sell'
    resources :comments, only: [:create, :destroy, :edit, :update] do
      resources :replies, only: [:new, :create, :destroy, :edit, :update]
    end
  end
  resources :conversations, only: [:create] do
  	member do
  		post :close
  	end
  	resources :messages, only: [:create]
  end
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  resources :new_notifications
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :book
  belongs_to :user
  has_many :replies, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_except_owner, only: %i[destroy]
  respond_to :js, :json, :html
  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save

    

    if @book.user_id != current_user.id
      @new_notification = NewNotification.create! user: @book.user, content: "#{current_user.username}님이 #{@book.bookname}책에 댓글을 달았습니다." ,content_truncate: "#{current_user.username}님이 #{@book.bookname}책에 댓글을 달았습니다.".truncate(20, omission: '...'), link: book_path(@book)
    end
    redirect_to "/books/#{@book.id}/#comment-#{@comment.id}"
  end

  def destroy
    print(@comment)
    @id = @comment.book.id
    @comment.destroy
    redirect_to "/books/#{@id}#comment-box"
  end
  def edit
    @comment = Comment.find(params[:id])

  end
  def update 
    @comment = Comment.find(params[:id])
    @book = @comment.book
    @comment.update(comment_params)
    redirect_to "/books/#{@book.id}/#comment-#{@comment.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :book_id, :secret)
  end
  def redirect_except_owner
    @comment = Comment.find(params[:id])
    if @comment.user.id != current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@comment.book, @comment], remote: true do |f| %>
  	 <strong><%= @comment.user.username %></strong> : <%= f.text_field :content, :autocomplete => :off %>
   	 <%= f.submit %>
<% end %>

app/views/comments/_item.html.erb
<li>  
	<div id="comment-<%=comment.id%>">
	<% if (comment.secret == true)  %>
		<% if (comment.user == current_user || comment.book.user == current_user) %>
		    <strong><%= comment.user.username %></strong> [비밀댓글] <%= comment.content %><br>
		    <% if comment.user == current_user %>
		    <%= link_to "삭제", book_comment_path(book, comment), method: :delete %>
		    <% end %>
		    <%= link_to "답글달기", new_book_comment_reply_path(book, comment), class: 'reply-comment-link', remote: true  %>
			<hr>
				<ul class="replies-comment-<%=comment.id%>">
					<% comment.replies.each do |reply| %>
						<%= render partial: "replies/item", locals: {book: @book, comment: comment, reply: reply } %>
					<% end %>
				</ul>
		 <% else %>
		 	<strong>비밀 댓글입니다.</strong>
		 <% end %>
	<% else %>
	    <strong><%= comment.user.username %></strong>  <%= comment.content %><br>
	    <% if comment.user == current_user %>
	    <%= link_to "삭제", book_comment_path(book, comment), id:'cmt', method: :delete %>
	    <% end %>
	    <%= link_to "답글달기", new_book_comment_reply_path(book, comment), id:'cmt', class: 'reply-comment-link', remote: true  %>
			<hr>
			<ul class="replies-comment-<%=comment.id%>">
				<% comment.replies.each do |reply| %>
				 <%= render partial: "replies/item", locals: {book: @book, comment: comment, reply: reply } %>
				<% end %>
			</ul>
	<% end %>
    </div>
</li>  

app/views/comments/create.js.erb
// (function($){
//     $("#comment_content").val("");
//     var html = "<%= escape_javascript(render(partial: 'comments/item', locals: {book: @book, comment: @comment})) %>";
//     $(".comments").append(html);
// })(jQuery)

app/views/comments/destroy.js.erb
(function($){
    $('#comment-<%= @comment.id %>').remove();
    $('.replies-comment-<%= @comment.id %>').remove();
})(jQuery)

app/views/comments/edit.js.erb
(function($){
    $('#comment-<%= @comment.id %>').html("<%= j render 'form' %>");
})(jQuery)

app/views/comments/update.js.erb
// (function($){
//     var html = "<%= escape_javascript(render(partial: 'comments/item', locals: {book: @book, comment: @comment})) %>";
//     $('#edit_comment_<%= @comment.id %>').replaceWith(html);
// })(jQuery)