config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#index'
  get 'books/find', as: 'books_find'
  get '/info/:info', to: 'books#info', as: 'find_info'
  get '/omypage', to: 'books#old_mypage', as: 'old_mypage'
  get '/mypage', to: 'books#mypage', as: 'mypage'
  get '/hello', to: 'books#introduction', as: 'intro'
  get '/sgmail', to: 'books#sgmail', as: 'sgmail'

  resources :books do
  	post '/like', to: 'books#like_toggle'
    post '/sell', to: 'books#sell'
    resources :comments, only: [:create, :destroy, :edit, :update] do
      resources :replies, only: [:new, :create, :destroy, :edit, :update]
    end
  end
  resources :conversations, only: [:create] do
  	member do
  		post :close
  	end
  	resources :messages, only: [:create]
  end
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  resources :new_notifications
end

app/models/book.rb
class Book < ApplicationRecord
  validates :bookname, presence: true
  validates :author, presence: true
  validates :price, presence: true
  validates :img_url, presence: true
  validates :content, presence: true

  serialize :img_url, Array
  mount_uploaders :img_url, ImageUploader
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!, :except => [:index, :find, :introduction, :sgmail]
	respond_to :js, :json, :html
	def index
		@books = Book.order('created_at DESC').page params[:page]
	end
	def new
		@book = Book.new
	end
	def info
		@search_results = Naver::Search.book(query: params[:info])
	end
	def create
		book = Book.new(book_params)
		book.user_id = current_user.id
		if params[:book][:cost].to_f != 0.0
			book.discount = ((params[:book][:cost].to_f - params[:book][:price].to_f) / params[:book][:cost].to_f * 100).round(2)
		end
		book.save
		redirect_to root_path
	end
	def destroy
		book = Book.find(params[:id])
		book.destroy
		notification = NewNotification.where(link: "/books/#{params[:id]}")
		notification.destroy_all
		redirect_to root_path
	end
	def show
		@book = Book.find(params[:id])
	end
	def like_toggle
		@book = Book.find(params[:book_id])
		like = Like.find_by(user_id: current_user.id, book_id: params[:book_id])
		if like.nil?
			Like.create(user_id: current_user.id, book_id: params[:book_id])
		else
			like.destroy
		end
	end
	def find
		search = params[:search]
	    if search.nil? || search.empty?
	      @books=Book.where(sell: false).order('created_at DESC').page params[:page]
	    else
	      @books = Book.where("author LIKE ? OR bookname LIKE ?", "%#{search}%", "%#{search}%").order('created_at DESC').page params[:page]
	    end
	end
	def sell
		@book = Book.find(params[:book_id])
		if @book.sell
			@book.sell = false
		else
			@book.sell = true
		end
		@book.save
	end
	def mypage
		@user = current_user
		@books = @user.books.page params[:page]
		@likes = @user.likes.page params[:page]
		@noti = @user.new_notifications.order('created_at DESC').all
 	end
	def old_mypage
		@user = current_user
		@books = @user.books.all
		@recent_books = @books.last(4)
		@likes = @user.likes.all
		@recent_likes = @likes.last(4)
 	end
    private
    def book_params
       params.require(:book).permit(:bookname, :author, :price, :content, {img_url: []})
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_div.html.erb
<style>
html {
	font-family: 'Nanum Square', 'Nanum Gothic', sans-serif;
}
  body {
    font-size: 16px;
    line-height: 26px;
    font-weight: 300;
  }

  .books_title {
    padding: 2rem !important;
    padding-bottom: 0rem;
  }

  #eachcard {
    padding: 0 0.5rem;
    height: 10rem;
    margin-bottom: 0.5rem;
  }

  .card-body {
    padding: 0rem;
    padding-top: 3%;
    width: 80%;
  }

  #eachcard a {
    display: flex;
    height: 100%;
    width: 100%;
  }

  .card-image-top {
    height: 100%;
  }

  .inner-image {
    height: 100%;
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center;
  }

  .choice > span {
    margin-right: 0.5%;
    margin-left: 0.5%;
    cursor: pointer;
}
  .choice span.active {
    color: rgb(72,72,72);
    font-weight: 800;
  }
  .nav-link#search2 {
    visibility: hidden;
  }
  .no_books {
    visibility: hidden;
    margin-top: 5%;
  }
  .choice {
    display: flex;
    justify-content: flex-end;
  }

  .choice > span {
    font-size: 0.9rem;
  }

  #discnt {
  color: red;
  }

  #won {
    font-weight: bold;
  }
  .card-title {
    text-align: center;
  }

  .card-text {
    display: flex;
    justify-content: center;
  }

  .card-text p {
    font-size: 0.85rem;
  }

/* media queries */
@media all and (min-width: 320px) and (max-width: 767px) {
  .card-text p {
    font-size: 0.9rem;
  }
  .card-body {
    padding-top: 0;
  }
  .card-title {
    font-size: 0.9rem;
  }
  main,
  .container {
    background-color: #fbfbfb;
    margin-bottom: -1rem;
  }
  .card {
    border: none;
  }
  .card-title {
    width:95%;
    padding-left: 1rem;
  }
  #eachcard {
    padding: 0 0.1rem;
    margin-bottom: 0.7rem;
    border:0;
    box-shadow: 0 1px 4px 0;
    color: hsla(0,0%,0%,0.1);
    border-radius: 0;
  }
  .footer {
    padding-top: 0rem !important;
  }
  .choice {
    padding-top: 2rem;
    margin-bottom: -2rem;
    margin-right: -1.5rem;
  }

}
@media all and (min-width: 768px) {
  .card {
    border: none;
  }
  .book_contents {
    padding: 1.2rem 0 10rem 0;
    min-height: 80vh;
  }

  .card-image-top {
    height: 200px;
    margin: 0 auto;
  }

  .card-body {
    margin: 0 auto;
  }

  .card-title {
    display: flex;
    flex-direction: column;
    justify-content: center;
    margin-bottom: 0.5rem;
    font-size: 0.9rem;
  }

  #eachcard {
    height: 330px;
  }

  #eachcard a {
    display: block;
  }

  .card-image-top {
    width: 100%;
  }

  .inner-image {
    height: 100%;
  }
  .choice {
    margin-bottom: -4rem;
    margin-top: 2rem;
  }
}
@media all and (min-width: 1200px) {
  .choice {
    margin-bottom: -4rem;
    margin-top: 4rem;
    margin-right: 5rem;
  }

}
.img-cover {
  height: 100%;
  z-index: 1;
  color: white;
  font-size: 1.2rem;
  font-weight: bolder;
  padding-top: 50%;
  background-color: rgba(0, 0, 0, 0.6);
}
</style>


<% books.each do |b| %>
<div class="col-12 col-xl-3 col-md-4 col-sm-6 card" id="eachcard">
  <%= link_to book_path(b.id)do %>
  <div class="card-image-top">
    <% if b.img_url.first %>
    <div class="inner-image" style="background-image: url(https://dsgut53a1wh4g.cloudfront.net/<%=b.img_url.first.path%>)">
    <% end %>
      <% if b.sell %>
      <div class="img-cover text-center">판매완료</div>
      <% end %>
    </div>
  </div>
  <div class="card-body">
    <div class="card-title"><%=b.bookname%> | <%= b.author%></div>
    <div class="card-text">
      <p id="won"><%= b.price%>원</p>
      <p id="discnt">
        <% if b.discount>=0 %>
        [<%= b.discount%>%&darr;]
        <% else %>
        [할인율 정보 없음]
        <% end %>
      </p>
    </div>
  </div>
  <% end %>
</div>
<% end %>

<script>
/*모바일에서는 사진 사이즈 잘되는데, 큰화면에서는 어떻게?*/
  $(document).ready(function () {
    var cw = $('.card-image-top').height();
    $('.card-image-top').css({'width': cw + 'px'});
  });
</script>

app/views/books/_footer.html.erb
<style>
html {
	font-family: 'Nanum Square', 'Nanum Gothic', sans-serif;
}
.links > a {
  font-size: 0.9rem;
}

.link, p {
  margin-right: 1%;
}

.footer {
  grid-column-start: 1;
  grid-column-end: 5;
  text-align: center;
  clear: both;
  position: relative;
  max-height: 180px;
}

.makers {
    font-size: 0.95rem;
    font-weight: 400;
    line-height: 1.3333333;
    margin-top: 5px;
    color: black;
}

.copyright {
    margin-bottom: 0;
    font-size: 0.8rem;
    line-height: 2;
    color: #8d8d8d;
}

</style>
<footer class="footer py-3">
<hr style="color: gray;">
  <div class="links px-3 py-2">
    <a class="link" href=<%= root_path%>>검색하기</a>
    <a class="link" href=<%= new_book_path%>>책 등록하기</a>
    <a class="link" href=<%= old_mypage_path%>>마이페이지</a>
    <a href="https://open.kakao.com/o/gG6hpVV">건의사항<a> 
    <!-- <a class="link" id="info" href=<%= intro_path %>>서비스소개</a> -->
  </div>
  <p class="copyright">&copy; 2018 <strong style="color:black;">Sogang Likelion 6th</strong>. All Rights Reserved.</p>
</footer> 

app/views/books/info.js.erb
(function($){
	function replaceAll(str, searchStr, replaceStr) {
	  return str.split(searchStr).join(replaceStr);
	}

	$('.info').empty();
	<% for i in 0..4 %>
		var title = "<%= @search_results.items[i].title %>";
		title = replaceAll(title, "&lt;b&gt;", "");
		title = replaceAll(title, "&lt;/b&gt;", "");
		var author = "<%=@search_results.items[i].author%>";
		author = replaceAll(author, "&lt;b&gt;", "");
		author = replaceAll(author, "&lt;/b&gt;", "");
		$('.info').append('<tr data-author="'+author+'" data-title="'+title+'" data-price = "<%= @search_results.items[i].price%>"><td><%=image_tag @search_results.items[i].image %></td>' + '<td><p>'+ title+ '</p></td><td><p>'+author+'</p></td><td><%=@search_results.items[i].price%></td></tr>');
	<% end %>
	<% for i in 5..9 %>
		var title = "<%= @search_results.items[i].title %>";
		title = replaceAll(title, "&lt;b&gt;", "");
		title = replaceAll(title, "&lt;/b&gt;", "");
		var author = "<%=@search_results.items[i].author%>";
		author = replaceAll(author, "&lt;b&gt;", "");
		author = replaceAll(author, "&lt;/b&gt;", "");
		$('.info').append('<tr style="display: none;" data-author="'+author+'" data-title="'+title+'" data-price = "<%= @search_results.items[i].price%>"><td><%=image_tag @search_results.items[i].image %></td>' + '<td><p>'+ title+ '</p></td><td><p>'+author+'</p></td><td><%=@search_results.items[i].price%></td></tr>');
	<% end %>
})(jQuery)

app/views/books/introduction.html.erb
<!-- 정원아 여기가 service 소개하는 뷰입니다. -->

app/views/books/like_toggle.js.erb
(function($){
    $('.like-btn').toggleClass('button2 button3');
    $('.like-btn').html('<i class="far fa-heart"></i>'+ <%=@book.likes.size%>);
})(jQuery)

app/views/books/new.html.erb
<style>
html, a, p {
	color: #1f2d3d;
}
html {
	font-family: 'Nanum Square','Nanum Gothic', sans-serif;
}

/*@font-face { font-family: 'KCC-eunyoung'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/KCC-eunyoung-Regular.woff') format('woff'); font-weight: normal; font-style: normal; }
*/

#banner {
  background-color: rgb(253,84,0);
  height: 280px;
  width: 100%;
}

@media all and (max-width: 992px){
	.submit-form .submit-form-content{
		width: 90%;
	}
}
@media all and (min-width: 992px) {
	.submit-form .submit-form-content{
		width: 40%;
	}
}
.new_nav {
	height: 50px;
	width: 100%;
	background-color: #fdd400;
	display: flex;
	align-items: center;
}

.form-control{
	padding: 0.6rem 0.75rem;
}


.form-control:focus {
  outline: none;
  border-color: #2c97de;
  box-shadow: 0 0 5px rgba(44, 151, 222, 0.2);
}

.submit-form{
	display: flex;
	justify-content: center;
	align-items: center;
}

.form-group{
	margin: 1.2rem 0;
}

.form-label {
	margin-bottom: 0.5rem;
	font-size: 1rem;
	color: #495057;
}
.main-label {
	font-size: 1.8rem;
	font-weight: bold;
	margin-left: 35%;
}

form {
	margin-top: 2%;
}

textarea {
	height: 200px;
}

legend {
	color: #495057 !important;
}

input[type=text],
textarea {
	border: 1px solid #cfd9db;
	border-radius: .25em;
	box-shadow: inset 0 1px 1px rgba(0,0,0,.08);
	padding: 12px;
}

.file-input {
  display: inline-block;
  text-align: left;
  background: #fff;
  padding: 16px;
  width: 450px;
  position: relative;
  border-radius: 3px;
}

.file-input > [type='file'] {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  z-index: 10;
  cursor: pointer;
}

.file-input > .button {
  display: inline-block;
  cursor: pointer;
  background: #eee;
  padding: 8px 16px;
  border-radius: 2px;
	margin-right: 8px;
	border: 1px solid #cfd9db;
	border-radius: .25em;
	box-shadow: 0 1px 1px rgba(0,0,0,.08);
	padding: 12px;
}

.file-input:hover > .button {
  background: dodgerblue;
	color: white;
	border: 1px solid #cfd9db;
	border-radius: .25em;
	box-shadow: 0 1px 1px rgba(0,0,0,.08);
	padding: 12px;
}

.file-input > .label {
  color: #333;
  white-space: nowrap;
  opacity: .3;
}

.file-input.-chosen > .label {
	color: rgb(253,84,0);
  opacity: 1;
}

.more-book:hover {
	color: black;
}

#mobilebtn {
  color: black !important;
}

p#discnt {
	font-size: 1.8rem;
	text-align: center;
	vertical-align: middle;
	line-height: 100%;
}
/*

.sidenav {
	right: 100px !important;
}
*/


/* media queries */
@media all and (min-width: 320px) and (max-width: 575px){

.file-input {
	width: 100%;
	padding: 0;
	margin-bottom: 5%;
}
 #mobilebtn {
	 margin-left:-1rem;
 }
 a.dropdown-toggle {
	 margin-left: -2rem;
 }
 .read {
	 width: auto !important;
 }
}
@media all and (min-width: 576px) and (max-width: 991px){

}
@media all and (min-width: 992px) {
}

@media all and (min-width: 1200px) {

}
#mobilebtn {
  color: black;
  visibility: visible;
}
#bar {
	color: #232741 !important;
}

</style>

<%= render 'nav2' %>
<div class="whole" style="margin-bottom: 5%;">
<%= render 'form', book: @book, path: books_path, form_method: 'post' %>
</div>
<%= render 'footer' %>

<script>
$(document).scroll(function() {
  if ($(window).scrollTop() > 350) {
  $('#mobilebtn').css('color','black');
}
  else {   
  $('#mobilebtn').css('color','black');
}      
});
	
	(function() {
	  $(document).on('click', '.more-book', function(e) {
	    e.preventDefault();
	    var p = $('.whole');
	    p.append("<%= j(render 'form', book: @book, path: books_path, form_method: 'post') %>");
	  });
	})();

// Also see: https://www.quirksmode.org/dom/inputfile.html

var inputs = document.querySelectorAll('.file-input')

for (var i = 0, len = inputs.length; i < len; i++) {
  customInput(inputs[i])
}

function customInput (el) {
  const fileInput = el.querySelector('[type="file"]')
  const label = el.querySelector('[data-js-label]')
  
  fileInput.onchange =
  fileInput.onmouseout = function () {
    if (!fileInput.value) return
    
    var value = fileInput.value.replace(/^.*[\\\/]/, '')
    el.className += ' -chosen'
    label.innerText = value
  }
}

$(document).ready(function () {
	$('.minititle span').text('책등록하기');
  
	var cw = $('input#book_author').height();
  $('input#book_bookname').css({'height': cw + 26 + 'px'});

});
</script>



app/views/books/sell.js.erb
(function($){
    $('.sell').toggleClass('button2 button1');
    $('.img-cover').toggle();
})(jQuery)

app/views/books/show.html.erb
<style>
html {
	font-family: 'Nanum Square','Nanum Gothic', sans-serif;
}
h4 {
	font-size: 1rem;
	font-weight: 600;
	color: rgb(59,56,56);
}

.content {
	background-color: white;
}
small {
	font-size: 1rem;
}
strong {
	font-weight: bold;
}
.book1 > p > strong {
	color: red;
}
.book-detail {
	font-size: 1.2rem;
	padding: 0 3.5rem;
}

.book-detail2 {
	margin-top: 2rem;
}	

#author {
	font-size: 0.8rem;
	color: gray;
}
.title { 
	margin-bottom: 30px;
	color: gray; 
}
.image,
.image2{
	height: 300px;
	background-size: contain;
  background-repeat: no-repeat;
  background-position: center;
}
.book-content {
	padding: 1rem 0;
}
.book1 > div > h1 {
	font-size: 1.5rem;
	font-weight: bold;
	margin-bottom: 5px;
}
.book1 > div > p { font-size: 1rem; }

.book2 {
	padding-top: 2%;
	padding-bottom: 2%;
}
/*
.book1, .book2, .book3 { 
	height: 100px;
	display: flex;
	flex-direction: column;
}
.book3 {
	height: 70px;
}
.book1 {
	justify-content: space-between;
}
.book2, .book3 {
	font-size: 1rem;
}
.book2 { justify-content: center; }
.book3 { justify-content: flex-start; }
.book2 > p, .book3 > p {
	margin: 5px 0;
}
*/
.content {
	margin-top: 0.5rem;
	padding: 15px;
	font-size: 1rem;
	min-height: 400px;
	border-radius: .28571429rem;
}
.button {
	width: 100%;
    background-color: rgba(164, 164, 164,0.5);
    border: none;
    outline: none;
    color: white;
    padding: 16px 32px;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    font-weight: bold;
    text-align: center;
}
.button1 {
	 border-radius: .28571429rem;
	 border: 1px solid rgba(164, 164, 164,0.5);
}
.button2 {
  background-color: rgba(0,0,0,0); 
  color: #A4A4A4; 
  border: 1px solid #A4A4A4;
  border-radius: .28571429rem;
}
.button2 .fa-heart {
  color: #A4A4A4;
}
.button3 {
	background-color: #fdd400; 
	border: 1px solid #fdd400;
  color: rgb(59,56,56); 
  border-radius: .28571429rem;
}
.button3 .fa-heart {
  color: #ff0000;
}
.button5 {
	color: red !important;
	border: 1px solid red;
	border-radius: .28571429rem;
	background-color: white;
}
.button5 > a:link {
	color: red !important;
}

#zzim {
	width: 100%; 
}

#mobilebtn {
  color: black !important;
}

a:hover {
	color: black;
}

#btns {
	padding: 0;
}

.inner_content {
	border: 1px solid rgba(0, 0, 0, 0.1);
	height: auto;
	padding: 1rem;
	margin: 1rem;
}
/* 위의 inner_content는 min-height가 있어야 하는데 아래는 없어야 하니까 구분해주기. */
.inner_content.maincontent {
	min-height: 600px;
	height: auto;
} 

.mainimg .image{
	background-size: contain;
  background-repeat: no-repeat;
	background-position: center;
	width: 50%;
}
}

.maincontent {
	display: flex;
	justify-content: center;
	text-align: center;
}

#cmt {
	font-size: 0.75rem;
	color: gray;
	margin-right: 1%;
}

/* media queries */
@media all and (min-width: 320px){

.mainimg .image{
	width: 90%;
	background-size: contain;
}
	.inner_content {
		margin: 0;
		padding: 0.5rem;
		border-right: none;
		border-left: none;
		border-top: none;
	}
	.book-detail {
		padding: 0 0.5rem;
	}
	.content {
		padding: 0;
	}
	#comment_content {
		width: 80% !important;
	}
	.submitbtn {
		width: 18% !important;
	}
	.cmtcreate {
		margin: 0.5rem;
	}
	.maincontent {
		margin: 0 !important;
	}
	.mainimg > .image {
	margin: 1rem auto;
	width: 100%;
}
.maincontent2 {
	margin: 2rem 0rem 4rem 0rem;
}

}
@media all and (min-width: 576px) and (max-width: 991px){
	.book-content {
		padding: 1rem;
}
.mainimg .image{
	width: 80%;
	background-size: contain;
}
	.inner_content {
		margin: 0;
		padding: 0.5rem;
	}
	#comment_content {
		width: 90% !important;
	}
	.submitbtn {
		width: 9% !important;
	}
}
@media all and (min-width: 992px) {
	.book-content {
		padding: 2rem;
	}

	.allbtn {
		display: flex;
		justify-content:space-between;
	}
	#btns {
		width: 49%;
	}
	.row {
		padding: 0 1.5rem;
	}
	.inner_content {
		margin: 0;
	}
.mainimg .image{
	width: 70%;
	background-size: contain;
}
	#comment_content {
		width: 92% !important;
	}
	.submitbtn {
		width: 7.5% !important;
	}
	.cmtcreate {
		margin: 0rem;
	}
}

@media all and (min-width: 1200px) {
	.book-content {
		padding: 2rem;
	}
	.row {
		padding: 0 1.5rem;
	}
	.title {
		margin-left: 6%;
	}
	.allbtn {
		display: flex;
		justify-content:space-between;
	}
	#btns {
		width: 49%;
	}
	.inner_content {
		padding: 2rem;
	}
	.book-detail {
		margin: 0 3rem;
		margin-top: 2rem;
	}
	#comment_content {
		width: 93% !important;
	}
	.submitbtn {
		width: 6.5% !important;
	}
	.cmtcreate {
		margin: 1rem;
	}
	.image {
	margin: 1rem auto;
	width: 40% !important;
}
.maincontent2 {
	margin: 2rem 2rem 5rem 2rem;
}
form.new_reply .repl {
	width: 7% !important;
}
}

.submitbtn {
	padding: 1.2rem 0;
	width: 6.5%;
	font-size: 1rem;
	border: 1px solid #fdd400;
	background-color: #fdd400;
	border-radius: .28571429rem;
}

#comment_content {
	margin: 0;
	border: 1px solid gray;
	padding: 1rem;
	width: 93%;
}

ul.comments > hr:last-child {
	border-top: none;
}

.img-cover {
	height: 100%;
	z-index: 1;
	color: white;
	font-size: 1.2rem;
	font-weight: bolder;
	padding-top: 50%;
	background-color: rgba(0, 0, 0, 0.6);
}

form.new_reply .repl {
	padding: 1.2rem 0;
	width: 20%;
	font-size: 1rem;
	border: 1px solid #fdd400;
	background-color: #fdd400;
	border-radius: .28571429rem;
}

.repl_content {
	border: 1px solid gray;
	padding: 1rem;
	margin: 0;
	width: 70%;
}
#bar {
  color: #232741 !important;
}


</style>

<header>
<%= render 'nav2' %>
</header>
<main>
	<div class="container">
		<div class="book-detail book-detail1">
			<div class="title"><h4>기본정보</h4><hr></div>
			<div class="row">
				<div class="col-sm-5 col-lg-4 col-xl-4" style="padding: 0;">
					<% if @book.img_url.first %>
					<div class="image2" style="background-image: url(https://dsgut53a1wh4g.cloudfront.net/<%=@book.img_url.first.path%>);">
					<% end %>
						<% if @book.sell %>
					    <div class="img-cover text-center">판매완료</div>
					    <% end %>
					</div>
				</div>
				<div class="col-sm-7 col-lg-8 col-xl-8 book-content">
					<div class="book1">
						<div><h2 style="font-weight: bold;"><%= @book.bookname%></h2><p id="author"><%= @book.author%> 지음</p></div>
					</div>
					<hr>
					<div class="book2">
						<p><span style="font-size: 0.9rem">판매가 : </span><strong style="color: blue; font-size: 1.2rem;"><%=@book.price %>원</strong> <span style="color: red; font-size: 0.9rem;">
							<% if @book.discount>=0 %>
					        [<%= @book.discount%>%&darr;]
					        <% else %>
					        [할인율 정보 없음]
					        <% end %>
						</span></p>
						<p><span style="font-size: 0.9rem">판매자 : <%= @book.user.username %> | <%= @book.user.school %> | <%= @book.user.studentid %>학번</span></p>
						<p><span style="font-size: 0.9rem">등록일 : <%= @book.user.created_at.strftime("%Y-%m-%d") %></span></p>
					</div>
					<hr>
					<div class="allbtn">
						<% if current_user == @book.user %>
						<div id="btns">
						  <% if @book.sell %>
						  <%= link_to '판매완료', book_sell_path(@book), method: :post, remote: true, class: 'button button1 sell' %>
						  <% else %>
						  <%= link_to '판매완료', book_sell_path(@book), method: :post, remote: true, class: 'button button2 sell' %>
						  <% end %>
						</div>
						<div id="btns">
							<%= link_to '삭제하기', book_path(@book), method: :delete, class: 'button button5' %>
							<% else %>
						<% if current_user.is_like?(@book) %>
							<%= link_to book_like_path(@book), method: :post, remote: true, class: 'button button3 like-btn', id:'zzim' do %>
								<i class="far fa-heart"></i><%=@book.likes.size %>
							<% end %>
							<% else %>
							<%= link_to book_like_path(@book), method: :post, remote: true, class: 'button button2 like-btn',id:'zzim' do %>
								<i class="far fa-heart"></i><%=@book.likes.size %>
							<% end %>
							<% end %>
						</div>	
						<% end %>		
					</div>
				</div>
			</div>		
		</div>
			<div class="book-detail book-detail2">
				<h4>상세정보</h4>
				<hr>	
				<div class="content">
					<div class="inner_content maincontent">
					<!-- 정원아 여기야! -->
						<div class="mainimg">
							<% @book.img_url.each do |x| %>
								<% if x %>
									<div class="image eachimg" style="background-image: url(https://dsgut53a1wh4g.cloudfront.net/<%=x.path%>);"></div>
								<% end %>
							<% end %>
						</div>
						<div class="maincontent2">
							<p><%= @book.content %></p>
						</div>
					</div>
				</div>
			</div>	
			<div class="book-detail book-detail2">
				<h4 id="comment-box">댓글</h4>
				<div class="content">
					<div class="inner_content" style="padding-bottom: 0.1rem; padding-top: 0.1rem;">
						<ul class="comments" style="margin:0.5rem;">
        			<% @book.comments.each do |comment| %>
        				<%= render partial: "comments/item", locals: { book: @book, comment: comment } %>
        				<div id="comment-<%=comment.id%>-replyform", class="ml-2"></div>
								<hr>
        			<% end %>
    				</ul> 
					</div>
			  	<!-- 댓글생성 -->
					<div class="cmtcreate">
						<%= form_for [@book, @book.comments.new], remote: true do |f| %>
							<div class="top">
				  			<%= f.text_field :content, :autocomplete => :off,:required => true %>
				  			<%= f.submit "작성",class:'submitbtn' %>
							</div>
							<div class="bottom" style="text-align: right; margin: 0.5rem 0">
				  			<%= f.check_box(:secret) %>
				  			<%= label_tag(:secret, '비밀댓글') %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
	</div>
</main>
<%= render 'footer' %>

<script>
$(document).scroll(function() {
  if ($(window).scrollTop() > 350) {
  $('#mobilebtn').css('color','black');
}
  else {   
  $('#mobilebtn').css('color','black');
}      
});
  $(document).ready(function () {
		$('.minititle span').text('상세보기');

    var mw = $('.eachimg').width();
    $('.eachimg').css({'height': mw + 'px'});
  });
</script>